# Generated by Django 3.2.18 on 2023-03-05 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('date_arrive', models.DateField()),
                ('date_leave', models.DateField()),
                ('adults_num', models.IntegerField()),
                ('child_num', models.IntegerField()),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_arrive'],
            },
        ),
        migrations.CreateModel(
            name='MakeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('comment_message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='MakeEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('heading', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('message_body', models.TextField()),
                ('auto_acknowledge', models.BooleanField(default=False)),
                ('date_submitted', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.AddIndex(
            model_name='makeenquiry',
            index=models.Index(fields=['-date_submitted'], name='motorhomepa_date_su_a9d5ef_idx'),
        ),
        migrations.AddField(
            model_name='makecomment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-date_arrive'], name='motorhomepa_date_ar_ac582d_idx'),
        ),
    ]
