# Generated by Django 3.2.18 on 2023-03-14 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motorhomepark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SiteCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('slots_used', models.IntegerField()),
                ('order_status', models.CharField(choices=[('draft', 'Draft'), ('confirm', 'Confirm'), ('cancel', 'Cancel')], default='draft', max_length=10)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motorhomepark.booking')),
            ],
            options={
                'ordering': ['booking_date', 'order_status'],
            },
        ),
        migrations.AddIndex(
            model_name='sitecapacity',
            index=models.Index(fields=['booking_date', 'order_status', 'slots_used'], name='motorhomepa_booking_6af728_idx'),
        ),
    ]
