# Generated by Django 3.2.18 on 2023-03-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorhomepark', '0002_auto_20230315_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
