# Generated by Django 3.2.18 on 2023-03-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorhomepark', '0002_auto_20230314_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecapacity',
            name='person',
        ),
        migrations.AlterField(
            model_name='makeenquiry',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
