# Generated by Django 3.2.18 on 2023-03-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorhomepark', '0003_alter_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeenquiry',
            name='slug',
        ),
    ]
