# Generated by Django 3.2.18 on 2023-03-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorhomepark', '0003_auto_20230315_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='name_id',
        ),
    ]
