# Generated by Django 3.2.18 on 2023-03-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorhomepark', '0004_remove_makeenquiry_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
