# Generated by Django 3.2.18 on 2023-03-23 12:49

from django.db import migrations, models
import motorhomepark.models


class Migration(migrations.Migration):

    dependencies = [
        ('motorhomepark', '0005_alter_booking_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_arrive',
            field=models.DateField(validators=[motorhomepark.models.validate_date]),
        ),
    ]
