# Generated by Django 3.2.18 on 2023-03-24 20:48

from django.db import migrations, models
import motorhomepark.models


class Migration(migrations.Migration):

    dependencies = [
        ('motorhomepark', '0006_alter_booking_date_arrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adults_num',
            field=models.IntegerField(validators=[motorhomepark.models.validate_adults]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='child_num',
            field=models.IntegerField(validators=[motorhomepark.models.validate_children]),
        ),
    ]
