# Generated by Django 3.2.18 on 2023-07-07 15:49

from django.db import migrations, models
import motorhomepark.models


class Migration(migrations.Migration):

    dependencies = [
        ('motorhomepark', '0007_auto_20230324_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_leave',
            field=models.DateField(validators=[motorhomepark.models.validate_date]),
        ),
    ]
